# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-10 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assestment',
            name='username',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
