# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assestment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='assestment',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 8, 13, 9, 29, 57, 913146, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
