# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_assignment_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='excel',
            field=models.FileField(blank=True, upload_to='excel_doc'),
        ),
    ]
