# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_userprofile_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 13, 14, 10, 18, 559557, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
