# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_userprofile_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uploaded_at',
        ),
    ]
