# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0012_auto_20170814_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
