# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0014_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(default='NA', upload_to='documents/'),
        ),
    ]
