# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0016_auto_20170823_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 8, 23, 7, 21, 20, 58557, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
