# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0017_document_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date',
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 23, 8, 55, 3, 896355, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
