# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 11:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0018_auto_20170823_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assestment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
